version: '3.8'

services:
  app:
    build:
      dockerfile: php-apache-mysqli-dockerfile
      context: .
    image: php-apache-mysqli:1
    container_name: app
    restart: always
    ports:
      - 80:80
    volumes:
      - /data/app-web-docker:/var/www/html
    networks:
      - dbnet
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - /data/db-web-docker:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Senha@123
      MYSQL_ROOT_PASSWORD: Senha@321
    networks:
      - dbnet
    expose:
      - 3306

networks:
  dbnet:
