apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-k8s-backend-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: lab-k8s-backend
  template:
    metadata:
      labels:
        app: lab-k8s-backend
    spec:
      containers:
      - name: lab-k8s-backend
        image: reginaldovillela/lab-k8s-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: lab-k8s-backend-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: lab-k8s-backend
  ports:
  - port: 80
    targetPort: 80
