# apiVersion: v1
# kind: Pod
# metadata:
#   name: lab-k8s-database
#   labels:
#     name: lab-k8s-database
# spec:
#   containers:
#   - name: lab-k8s-database
#     image: reginaldovillela/lab-k8s-database:1.0
#     imagePullPolicy: Always
#     ports:
#       - containerPort: 3306
#     volumeMounts:
#       - name: db-local
#         mountPath: /var/lib/mysql
#   volumes:
#     - name: db-local
#       persistentVolumeClaim:
#         claimName: db-local

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-cicd-gitlab-database
spec:
  selector:
    matchLabels:
      app: lab-cicd-gitlab-database
  template:
    metadata:
      labels:
        app: lab-cicd-gitlab-database
    spec:
      containers:
      - name: lab-cicd-gitlab-database
        image: mysql:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-local
          mountPath: /var/lib/mysql
      volumes:
      - name: db-local
        persistentVolumeClaim:
          claimName: db-local
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_DATABASE

---

apiVersion: v1
kind: Service
metadata:
  name: lab-k8s-database-conn
spec:
  ports:
  - port: 3306
  selector:
    app: lab-k8s-database
  clusterIP: None
