apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-local
  labels:
    type: sb-local
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-local
spec:
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
